CREATE TABLE IF NOT EXISTS Users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(120) NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Workspaces(
  id VARCHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  user_id REFERENCES Users(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS Channels(
  id VARCHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  user_id VARCHAR(36) REFERENCES Users(id) NOT NULL,
  workspace_id VARCHAR(36) REFERENCES Workspaces(id) NOT NULL,
  topic TEXT DEFAULT '',
  description TEXT DEFAULT '',
  is_private BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Messages(
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) REFERENCES Users(id) NOT NULL,
  channel_id VARCHAR(36) REFERENCES Channels(id) NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- CREATE TABLE IF NOT EXISTS Pages (
--     id VARCHAR(36) PRIMARY KEY,
--     user_id VARCHAR(36) REFERENCES Users(id) ON DELETE CASCADE,
--     bio TEXT,
--     backgroung_color TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS Links (
--   id VARCHAR(36) PRIMARY KEY,
--   page_id VARCHAR(36) REFERENCES Pages(id) ON DELETE CASCADE,
--   name TEXT,
--   url TEXT,
--   active BOOLEAN DEFAULT TRUE
-- );

/* PG Session Middleware */
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
  "sess" json NOT NULL,
  "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX "IDX_session_expire" ON "session" ("expire");
/* End PG Session Middleware */